#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

if command -v cljstyle &> /dev/null
then
    echo "Running cljstyle on pre-commit hook"
    echo "Will check files $(git diff --name-only --cached)"
    echo "$(cljstyle version)"
    cljstyle fix `git diff --name-only --cached`
    git add `git diff --name-only --cached`
    exit 0
fi

