(ns ^:deprecated contrib.stacktrace
  "Deprecated: moved to dustingetz.stacktrace"
  (:require [dustingetz.stacktrace]))

(def ->frame dustingetz.stacktrace/->frame)
(def anonymous? dustingetz.stacktrace/anonymous?)
(def to-canonical-string dustingetz.stacktrace/to-canonical-string)
(def IDENTIFIER-PATTERN dustingetz.stacktrace/IDENTIFIER-PATTERN)
(def V8-ALIAS-PATTERN dustingetz.stacktrace/V8-ALIAS-PATTERN)
(def V8-CONTEXT-PATTERN dustingetz.stacktrace/V8-CONTEXT-PATTERN)
(def V8-FUNCTION-NAME-PATTERN dustingetz.stacktrace/V8-FUNCTION-NAME-PATTERN)
(def V8-FUNCTION-CALL-PATTERN dustingetz.stacktrace/V8-FUNCTION-CALL-PATTERN)
(def URL-PATTERN dustingetz.stacktrace/URL-PATTERN)
(def CHROME-URL-PATTERN dustingetz.stacktrace/CHROME-URL-PATTERN)
(def V8-STACK-FRAME-REGEXP dustingetz.stacktrace/V8-STACK-FRAME-REGEXP)
(def FIREFOX-FUNCTION-CALL-PATTERN dustingetz.stacktrace/FIREFOX-FUNCTION-CALL-PATTERN)
(def FIREFOX-STACK-FRAME-REGEXP dustingetz.stacktrace/FIREFOX-STACK-FRAME-REGEXP)
(def OPERA-ANONYMOUS-FUNCTION-NAME-PATTERN dustingetz.stacktrace/OPERA-ANONYMOUS-FUNCTION-NAME-PATTERN)
(def OPERA-FUNCTION-CALL-PATTERN dustingetz.stacktrace/OPERA-FUNCTION-CALL-PATTERN)
(def OPERA-STACK-FRAME-REGEXP dustingetz.stacktrace/OPERA-STACK-FRAME-REGEXP)
(def IE-FUNCTION-CALL-PATTERN dustingetz.stacktrace/IE-FUNCTION-CALL-PATTERN)
(def IE-STACK-FRAME-REGEXP dustingetz.stacktrace/IE-STACK-FRAME-REGEXP)
(def parse-stack-frame dustingetz.stacktrace/parse-stack-frame)
(def maybe-deobfuscate-function-name dustingetz.stacktrace/maybe-deobfuscate-function-name)
(def html-escape dustingetz.stacktrace/html-escape)
(def frames-to-string dustingetz.stacktrace/frames-to-string)
(def parse dustingetz.stacktrace/parse)
(def canonicalize dustingetz.stacktrace/canonicalize)
