(ns ^:deprecated contrib.trace3
  "Deprecated: moved to dustingetz.trace3"
  (:require [dustingetz.trace3])
  #?(:cljs (:require-macros
             #_{:clj-kondo/ignore [:deprecated-namespace]}
             contrib.trace3)))

(def current dustingetz.trace3/current)
(def !db dustingetz.trace3/!db)
(def db dustingetz.trace3/db)
(def !measure dustingetz.trace3/!measure)
(def measure dustingetz.trace3/measure)
(def !q dustingetz.trace3/!q)
(def q dustingetz.trace3/q)
(def ->trace-id dustingetz.trace3/->trace-id)
(def ->stamp dustingetz.trace3/->stamp)
(def ->id dustingetz.trace3/->id)
#?(:clj (def insert-trace dustingetz.trace3/insert-trace))
(def save-trace dustingetz.trace3/save-trace)
(def push-trace dustingetz.trace3/push-trace)
(def save-trace! dustingetz.trace3/save-trace!)
(def ->stable-trace-id dustingetz.trace3/->stable-trace-id)
(def Trace dustingetz.trace3/Trace)
(defmacro trace [& args] `(dustingetz.trace3/trace ~@args))
(def ->queue dustingetz.trace3/->queue)
#?(:clj (def save-traces dustingetz.trace3/save-traces))
(def SendClientTraces dustingetz.trace3/SendClientTraces)
(defmacro with-defaults [& body] `(dustingetz.trace3/with-defaults ~@body))
#?(:clj (def get-latest-pretty-v dustingetz.trace3/get-latest-pretty-v))
(def ->pretty dustingetz.trace3/->pretty)
(def RenderPoint dustingetz.trace3/RenderPoint)
(def pixel-secs dustingetz.trace3/pixel-secs)
(def RenderPointHistory dustingetz.trace3/RenderPointHistory)
(def RenderHistory dustingetz.trace3/RenderHistory)
#?(:clj (def ->origin dustingetz.trace3/->origin))
(def Header dustingetz.trace3/Header)
(def grid-color dustingetz.trace3/grid-color)
(def time-str dustingetz.trace3/time-str)
#?(:clj (def measure-distance dustingetz.trace3/measure-distance))
(def Throttle dustingetz.trace3/Throttle)
(def TraceView dustingetz.trace3/TraceView)
